// <auto-generated />
using System;
using HOMSys.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOMSys.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829062142_AddSalesOrderLineOosSync")]
    partial class AddSalesOrderLineOosSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOMSys.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] != ''");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddrLn1")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("AddrLn2")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("AliasKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("BlockInv")
                        .HasColumnType("bit");

                    b.Property<int>("CCode")
                        .HasColumnType("int");

                    b.Property<string>("CKey")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CZone")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ConsoMax2")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CsMan")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("CustWhse")
                        .HasColumnType("int");

                    b.Property<string>("DelAddrLn1")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("DelAddrLn2")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("DelArea")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("DelWhse")
                        .HasColumnType("int");

                    b.Property<bool>("ExBranch")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("IEffDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Offshore")
                        .HasColumnType("bit");

                    b.Property<int>("OldCCode")
                        .HasColumnType("int");

                    b.Property<int>("Salesman")
                        .HasColumnType("int");

                    b.Property<int>("ServeWh")
                        .HasColumnType("int");

                    b.Property<string>("Subd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<int>("TermDays")
                        .HasColumnType("int");

                    b.Property<string>("Tin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Tpc")
                        .HasColumnType("bit");

                    b.Property<string>("VatId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("WhseNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CusName");

                    b.HasIndex("CustKey")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.CustomerIdentifierMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("CustomerIdentifierMaps");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.CustomerZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CZone")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Branch");

                    b.HasIndex("CustKey");

                    b.ToTable("CustomerZones");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasFilter("[Code] != ''");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.DocClass", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("DocClasses");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create, edit, and delete users",
                            Key = "users",
                            Name = "User Management"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create, edit, and delete roles",
                            Key = "roles",
                            Name = "Role Management"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Configure role-based access to pages",
                            Key = "authorization",
                            Name = "Authorization Management"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Create, edit, and delete companies",
                            Key = "companies",
                            Name = "Company Management"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create, edit, and delete departments",
                            Key = "departments",
                            Name = "Department Management"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Create, edit, and delete sites",
                            Key = "sites",
                            Name = "Site Management"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Create, edit, and delete site types",
                            Key = "site-types",
                            Name = "Site Type Management"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Encode and view sales orders",
                            Key = "sales-orders",
                            Name = "Sales Order Encoding"
                        });
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.PoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PoDate")
                        .HasColumnType("date");

                    b.Property<string>("PoNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("SoId")
                        .HasColumnType("int");

                    b.Property<int?>("SoNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoNum");

                    b.HasIndex("SoId");

                    b.ToTable("PoLogs");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Effective")
                        .HasColumnType("date");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NpAfVat")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ProdNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdNo");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CProdNo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InnerQty")
                        .HasColumnType("int");

                    b.Property<decimal?>("NewPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("OldPrice1")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PriceFrom")
                        .HasColumnType("date");

                    b.Property<bool>("PriceList")
                        .HasColumnType("bit");

                    b.Property<string>("ProdDesc")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("ProdNo")
                        .HasColumnType("int");

                    b.Property<int>("QtyPerPc")
                        .HasColumnType("int");

                    b.Property<decimal?>("Srp")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Supplier")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("Um")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("CProdNo")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "",
                            Description = "Full system access",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        });
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<int>("SoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoId"));

                    b.Property<bool?>("Allocate")
                        .HasColumnType("bit");

                    b.Property<int?>("BirFrom")
                        .HasColumnType("int");

                    b.Property<int?>("BirNo")
                        .HasColumnType("int");

                    b.Property<int?>("BirTo")
                        .HasColumnType("int");

                    b.Property<string>("BlNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CCode")
                        .HasColumnType("int");

                    b.Property<string>("CKey")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("CancelDate")
                        .HasColumnType("date");

                    b.Property<string>("CauseFail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Cewit")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ChainCl")
                        .HasColumnType("int");

                    b.Property<string>("ChainCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("ChargeType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CheckDate1")
                        .HasColumnType("date");

                    b.Property<string>("CheckNo1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("ChkDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Cl")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CrAuthor")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsMan")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal?>("CurSlAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("CurrPay")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("CurrentSo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("CustWhse")
                        .HasColumnType("int");

                    b.Property<int?>("DcsNo")
                        .HasColumnType("int");

                    b.Property<string>("DelArea")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("DelWhse")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Delivered")
                        .HasColumnType("date");

                    b.Property<string>("Depot")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DocClass")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("DocNo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DpiDate")
                        .HasColumnType("date");

                    b.Property<int?>("DpiNo")
                        .HasColumnType("int");

                    b.Property<int?>("DrNo")
                        .HasColumnType("int");

                    b.Property<string>("Driver")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("Drops")
                        .HasColumnType("int");

                    b.Property<string>("DrpCust")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<decimal?>("DssAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly?>("DssDate")
                        .HasColumnType("date");

                    b.Property<string>("DssNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateOnly?>("Eda2")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Edd")
                        .HasColumnType("date");

                    b.Property<string>("Elapsed")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("ExBranch")
                        .HasColumnType("bit");

                    b.Property<bool>("ExpectDel")
                        .HasColumnType("bit");

                    b.Property<bool?>("ExtWhse")
                        .HasColumnType("bit");

                    b.Property<decimal?>("FccosAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("FccosNo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FccrDate")
                        .HasColumnType("date");

                    b.Property<int?>("GrNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("InvAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly?>("InvDate")
                        .HasColumnType("date");

                    b.Property<int?>("InvNo")
                        .HasColumnType("int");

                    b.Property<string>("InvRem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("InvTax")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("Invoice1")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPsuedoSo")
                        .HasColumnType("bit");

                    b.Property<string>("JobberCKey")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("JobberWhse")
                        .HasColumnType("int");

                    b.Property<int?>("MjReqNo")
                        .HasColumnType("int");

                    b.Property<bool?>("Moe")
                        .HasColumnType("bit");

                    b.Property<bool>("Offshore")
                        .HasColumnType("bit");

                    b.Property<string>("OldCsMan")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("OldSMan")
                        .HasColumnType("int");

                    b.Property<int?>("OldWhseNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrAmt")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("OrAmt1")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly?>("OrDate1")
                        .HasColumnType("date");

                    b.Property<int?>("OrNo")
                        .HasColumnType("int");

                    b.Property<int?>("OrNo1")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int?>("OrigSo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PassDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PendingSo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly?>("PickListed")
                        .HasColumnType("date");

                    b.Property<int?>("PickNo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PickTDate")
                        .HasColumnType("date");

                    b.Property<string>("PlateNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("PoDate")
                        .HasColumnType("date");

                    b.Property<int?>("PoNo")
                        .HasColumnType("int");

                    b.Property<string>("PoNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("PrintFccor")
                        .HasColumnType("bit");

                    b.Property<bool?>("Promodel")
                        .HasColumnType("bit");

                    b.Property<bool?>("RFlag")
                        .HasColumnType("bit");

                    b.Property<int?>("RTotCs")
                        .HasColumnType("int");

                    b.Property<int?>("RTotPc")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("ReasonCode")
                        .HasColumnType("int");

                    b.Property<decimal?>("RefRgwAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly?>("RefRgwDate")
                        .HasColumnType("date");

                    b.Property<int?>("RefRgwNo")
                        .HasColumnType("int");

                    b.Property<int?>("RefSoReq")
                        .HasColumnType("int");

                    b.Property<string>("Rem1")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Rem2")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Rem3")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Rfc4Rgw")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RrDate")
                        .HasColumnType("date");

                    b.Property<int?>("RrNo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RsrDate")
                        .HasColumnType("date");

                    b.Property<int?>("RsrNo")
                        .HasColumnType("int");

                    b.Property<int>("Salesman")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ServeDate")
                        .HasColumnType("date");

                    b.Property<int?>("ServeWh")
                        .HasColumnType("int");

                    b.Property<string>("ShipToLn1")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("ShipToLn2")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("SoElapsed")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("SoNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SoTymEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SoTymStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceFileHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatDesc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SubdName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SubdSMan")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SysDate")
                        .HasColumnType("date");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<int>("TermDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Tpc")
                        .HasColumnType("bit");

                    b.Property<int?>("TrType")
                        .HasColumnType("int");

                    b.Property<int?>("TransInv")
                        .HasColumnType("int");

                    b.Property<string>("TransTag")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateOnly?>("Transmit")
                        .HasColumnType("date");

                    b.Property<string>("Trucker")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Van")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VatId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Vessel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VhType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool?>("VisMin")
                        .HasColumnType("bit");

                    b.Property<string>("Voyage")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateOnly?>("VsDate")
                        .HasColumnType("date");

                    b.Property<int?>("VsNo")
                        .HasColumnType("int");

                    b.Property<string>("VsRemarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WaybillNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("WhseNo")
                        .HasColumnType("int");

                    b.Property<bool?>("WithVat")
                        .HasColumnType("bit");

                    b.HasKey("SoId");

                    b.HasIndex("CustKey");

                    b.HasIndex("OrderDate");

                    b.HasIndex("PoNum");

                    b.HasIndex("SoNo");

                    b.HasIndex("SourceFileHash");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.SalesOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllocatedQtyCs")
                        .HasColumnType("int");

                    b.Property<int?>("AllocatedQtyPc")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool?>("AutoFree")
                        .HasColumnType("bit");

                    b.Property<string>("Batch")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CProdNo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CSupplier")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("Cash2C")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Cash2S")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount1")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount1C")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount1S")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount2C")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount2S")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount3C")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount3S")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Discount4")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("DocNo")
                        .HasColumnType("int");

                    b.Property<int?>("DpAgeNo")
                        .HasColumnType("int");

                    b.Property<string>("DrpCust")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("EpCs")
                        .HasColumnType("int");

                    b.Property<decimal?>("F10430")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly?>("FgDiscType")
                        .HasColumnType("date");

                    b.Property<int?>("FgQtyCs")
                        .HasColumnType("int");

                    b.Property<int?>("FgQtyPc")
                        .HasColumnType("int");

                    b.Property<decimal?>("Free1C")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Free1S")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool?>("FreeAdd")
                        .HasColumnType("bit");

                    b.Property<bool>("FreeGoods")
                        .HasColumnType("bit");

                    b.Property<bool?>("FreeProd")
                        .HasColumnType("bit");

                    b.Property<decimal?>("FreeQCs1")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal?>("FreeQCs2")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int?>("FreeQPc1")
                        .HasColumnType("int");

                    b.Property<int?>("FreeQPc2")
                        .HasColumnType("int");

                    b.Property<int?>("InvNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("JobArea")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("NetAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("OldAmt")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("OldCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("OrigQtyCs")
                        .HasColumnType("int");

                    b.Property<int?>("OrigQtyPc")
                        .HasColumnType("int");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("PriceList")
                        .HasColumnType("bit");

                    b.Property<string>("ProdDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProdNo")
                        .HasColumnType("int");

                    b.Property<int>("QtyCs")
                        .HasColumnType("int");

                    b.Property<int>("QtyPc")
                        .HasColumnType("int");

                    b.Property<int>("QtyPerPc")
                        .HasColumnType("int");

                    b.Property<int?>("RefSoReq")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RrDate")
                        .HasColumnType("date");

                    b.Property<int?>("RrNo")
                        .HasColumnType("int");

                    b.Property<int>("SoId")
                        .HasColumnType("int");

                    b.Property<int?>("StkFlag")
                        .HasColumnType("int");

                    b.Property<int>("Supplier")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tax")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("Taxable")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Uc")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Um")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<decimal?>("ZPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SoId", "LineNo");

                    b.ToTable("SalesOrderLines");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteTypeId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasFilter("[Code] != ''");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.SiteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] != ''");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SiteTypes");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "",
                            Email = "admin@homsys.local",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            MustChangePassword = true,
                            PasswordHash = "$2a$11$HWPtG2hulzuprKTyJrT/cOhS/k.aBx.7jJZJaRYwwVkbs5D5IUvAq",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Zone2AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddOn")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CProdNo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateOnly?>("EffDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FixAmt")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("Branch", "CProdNo", "CustKey");

                    b.ToTable("Zone2AddOns");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.ZoneAddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddOn")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CProdNo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CZone")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly?>("EffDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FixAmt")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("Branch", "CProdNo", "CZone");

                    b.ToTable("ZoneAddOns");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Department", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.PoLog", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany()
                        .HasForeignKey("SoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HOMSys.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.SalesOrderLine", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Site", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HOMSys.Domain.Entities.SiteType", "SiteType")
                        .WithMany()
                        .HasForeignKey("SiteTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.User", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("HOMSys.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("HOMSys.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HOMSys.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HOMSys.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HOMSys.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
